version: "3"
services:
  gpteam:
    build:
      context: .
      dockerfile:  ./Dockerfile
    platform: linux/amd64
    container_name: gpteam
    environment:
      - PORT=3000
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    working_dir: /app
    tty: true
